### ISSUE TITLE
Rename Pascal-P6

### ISSUE THREAD

**Issue by samiam951242** [JulStrat/primesieve-pas#2]
Hi, sorry for putting this here, but your Pascal-P6 repo is locked as read-only.

Is there a chance you could rename your Pascal-P6 repo? It shows up in searches for Pascal-P6, which is a project that I run.

Your Pascal-P6 is derived from my repo Pascal-P5, and is otherwise unrelated to (my) Pascal-P6, which is live and ongoing project under development.

I realize that at the time you created your repo that my Pascal-P6 didn't exist, but there were several mentions in the documentation for Pascal-P5, which your project was based on, that I was working on Pascal-P6.

Since your Pascal-P6 is no longer a going concern, I wonder if you would consider a rename to eliminate any confusion between these projects. I am not asking for you to eliminate your repo, just a mild name name change to prevent confusion, like Pascal-Dijkstra.

Thank you for your attention.
I was unable to find an email for you. If you are interested in contacting me directly it is
samiam@moorecad.com

**Comment by JulStrat** [comment]
Hi, samiam.
I have created my **p6mach** (not Pascal-P6) repository 5 years ago just for historical reasons.
So I think you are wrong.

Regards.

**Comment by samiam95124** [comment]
I don't have an issue with that (p6mach). However, the description for the project reads:

"Pascal P6 compiler and interpreter by Richard Sprague"

Also the readme starts:

"This readme.txt file is for the purpose of explaining the contents of the
downloaded P6.zip file.

pcom.pas

pcom.pas is an expanded source of the Pascal P6 compiler"

Mr.  Sprague specifically created the project as a fork of my project, Pascal-P5, and named it "Pascal-P6", even though the Pascal-P5 project documentation specifically said that I was working on a successor project, Pascal-P6, at the time he forked the project.

Note that Pascal-P5 is more than 10 years old (it started on sourceforge, before github was created).

The issue is that a search in github off "pascal-p6" shows your repo as the second project after mine:

===================================================
[samiam95124/Pascal-P6](https://github.com/samiam95124/Pascal-P6)
6th version of Niklaus Wirth's original Pascal language compiler system
Pascal
·
[25](https://github.com/samiam95124/Pascal-P6/stargazers)
·
Updated 2 days ago

[JulStrat/p6mach](https://github.com/JulStrat/p6mach)
Public archive
Pascal P6 compiler and interpreter by Richard Sprague
Pascal
·
[4](https://github.com/JulStrat/p6mach/stargazers)
·
Updated on Sep 14, 2019

======================================================

And thus has the potential to confuse users. I don't have any rights to the name here, but
there is the common courtesy of not naming an incompatible fork of my own project with the
same name as my project, and gratitude for my having supplied the code that your repo is
based on.

As you say, p6mach is enough of a difference not to be confused. If you could, a simple change
to the project description on your repo:

About
Pascal P6 compiler and interpreter by Richard Sprague

To something other than "Pascal P6 compiler and interpreter" would do it.

Thanks for your attention.

Scott Franco
San Jose, CA

**Comment by JulStrat** [comment]
Repo description changed.

**Comment by samiam95124** [comment]
That did the job. Thanks so much.

Scott Franco
